#!/bin/sh
# Test the parser.
# Run this with the path to an input file like:
# $ scripts/parse-test tests/parser/legal/legal-01

runscanner() {
  $(git rev-parse --show-toplevel)/run.sh -t scan `pwd`/$1
}

runparser() {
  $(git rev-parse --show-toplevel)/run.sh -t parse --debug `pwd`/$1
}

infile=$1
echo "-- TOKENS --"
runscanner $infile
echo "-- INPUT --"
cat $infile
echo "-- PARSE --"
runparser $infile
